/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author davis
 */
public class Cardapio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Cardapio_GUI
     */
    public Cardapio_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        combos_btn = new javax.swing.JButton();
        bebidas_btn = new javax.swing.JButton();
        sobremesas_btn = new javax.swing.JButton();
        acompanhamento_btn = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lista_txt = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        total_txt = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        escolhaHamburguer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        combos_btn.setBackground(new java.awt.Color(255, 255, 255));
        combos_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/business.png"))); // NOI18N
        combos_btn.setFocusPainted(false);
        combos_btn.setFocusable(false);
        combos_btn.setOpaque(false);
        jPanel2.add(combos_btn);
        combos_btn.setBounds(30, 390, 110, 80);

        bebidas_btn.setBackground(new java.awt.Color(255, 255, 255));
        bebidas_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bebidas_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/soft-drink.png"))); // NOI18N
        bebidas_btn.setFocusPainted(false);
        bebidas_btn.setFocusable(false);
        bebidas_btn.setOpaque(false);
        bebidas_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bebidas_btnActionPerformed(evt);
            }
        });
        jPanel2.add(bebidas_btn);
        bebidas_btn.setBounds(30, 120, 110, 80);

        sobremesas_btn.setBackground(new java.awt.Color(255, 255, 255));
        sobremesas_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ice-cream.png"))); // NOI18N
        sobremesas_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobremesas_btnActionPerformed(evt);
            }
        });
        jPanel2.add(sobremesas_btn);
        sobremesas_btn.setBounds(30, 210, 110, 80);

        acompanhamento_btn.setBackground(new java.awt.Color(255, 255, 255));
        acompanhamento_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fried-potatoes.png"))); // NOI18N
        acompanhamento_btn.setDefaultCapable(false);
        acompanhamento_btn.setFocusable(false);
        acompanhamento_btn.setOpaque(false);
        jPanel2.add(acompanhamento_btn);
        acompanhamento_btn.setBounds(30, 300, 110, 80);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/150.png"))); // NOI18N
        jPanel2.add(logo);
        logo.setBounds(10, 0, 150, 110);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(-10, 0, 160, 490);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(null);

        lista_txt.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        lista_txt.setText("Lista");
        jPanel3.add(lista_txt);
        lista_txt.setBounds(20, 10, 330, 60);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(null);

        total_txt.setText("<variável-total>");
        jPanel4.add(total_txt);
        total_txt.setBounds(2, 2, 140, 60);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(430, 10, 140, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Total:");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(380, 30, 40, 14);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/delete(1).png"))); // NOI18N
        jButton1.setText("Cancelar Pedido");
        jButton1.setDefaultCapable(false);
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);
        jButton1.setBounds(250, 80, 220, 50);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/ecommerce(1).png"))); // NOI18N
        jButton2.setText("Finalizar Pedido");
        jButton2.setDefaultCapable(false);
        jButton2.setFocusPainted(false);
        jButton2.setFocusable(false);
        jButton2.setOpaque(false);
        jPanel3.add(jButton2);
        jButton2.setBounds(20, 80, 220, 50);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/trolley.png"))); // NOI18N
        jButton3.setDefaultCapable(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.setOpaque(false);
        jPanel3.add(jButton3);
        jButton3.setBounds(480, 80, 90, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 490, 580, 140);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/cheddar(1)(1).png"))); // NOI18N
        jButton4.setDefaultCapable(false);
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        jButton4.setOpaque(false);
        jPanel1.add(jButton4);
        jButton4.setBounds(360, 360, 140, 100);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/x carne(1)(1).png"))); // NOI18N
        jButton5.setDefaultCapable(false);
        jButton5.setFocusPainted(false);
        jButton5.setFocusable(false);
        jButton5.setOpaque(false);
        jPanel1.add(jButton5);
        jButton5.setBounds(190, 100, 140, 100);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/x queijo (2).png"))); // NOI18N
        jButton6.setDefaultCapable(false);
        jButton6.setFocusPainted(false);
        jButton6.setFocusable(false);
        jButton6.setOpaque(false);
        jPanel1.add(jButton6);
        jButton6.setBounds(360, 100, 140, 100);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/frango(1)(1).png"))); // NOI18N
        jButton7.setDefaultCapable(false);
        jButton7.setFocusPainted(false);
        jButton7.setFocusable(false);
        jButton7.setOpaque(false);
        jPanel1.add(jButton7);
        jButton7.setBounds(360, 230, 140, 100);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/bacon(1)(1).png"))); // NOI18N
        jButton8.setDefaultCapable(false);
        jButton8.setFocusPainted(false);
        jButton8.setFocusable(false);
        jButton8.setOpaque(false);
        jPanel1.add(jButton8);
        jButton8.setBounds(190, 230, 140, 100);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/tudo(1)(1).png"))); // NOI18N
        jButton9.setDefaultCapable(false);
        jButton9.setFocusPainted(false);
        jButton9.setFocusable(false);
        jButton9.setOpaque(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(190, 360, 140, 100);

        escolhaHamburguer.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        escolhaHamburguer.setText("Escolha Seu Hamburguer");
        jPanel1.add(escolhaHamburguer);
        escolhaHamburguer.setBounds(270, 0, 170, 60);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("X Cheddar");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(400, 340, 57, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("X Carne");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 80, 90, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("X Queijo");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(400, 80, 90, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("X Bacon");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(240, 210, 50, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("X Frango");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(400, 210, 50, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("X Tudo");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(240, 340, 50, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(578, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Fazer confirmação com JOptionPane
        //Agradecimento e voltar ao inicio
        new Iniciar_GUI().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bebidas_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bebidas_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bebidas_btnActionPerformed

    private void sobremesas_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobremesas_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sobremesas_btnActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cardapio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cardapio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cardapio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cardapio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cardapio_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acompanhamento_btn;
    private javax.swing.JButton bebidas_btn;
    private javax.swing.JButton combos_btn;
    public static javax.swing.JLabel escolhaHamburguer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    public static javax.swing.JTextField lista_txt;
    private javax.swing.JLabel logo;
    private javax.swing.JButton sobremesas_btn;
    public static javax.swing.JLabel total_txt;
    // End of variables declaration//GEN-END:variables
}
