/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author alunos
 */
public class opcoesPagamento_GUI extends javax.swing.JFrame {

    /**
     * Creates new form opcoesPagamento_GUI
     */
    public opcoesPagamento_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dinheiro_btn = new javax.swing.JButton();
        pagamentoPix_btn = new javax.swing.JButton();
        cartaoDebito_btn = new javax.swing.JButton();
        cartaoCredito_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<logo>");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 40, 110, 90);

        dinheiro_btn.setText("<dinheiro>");
        dinheiro_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dinheiro_btnActionPerformed(evt);
            }
        });
        jPanel1.add(dinheiro_btn);
        dinheiro_btn.setBounds(90, 450, 400, 80);

        pagamentoPix_btn.setText("<logo-pix>");
        pagamentoPix_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagamentoPix_btnActionPerformed(evt);
            }
        });
        jPanel1.add(pagamentoPix_btn);
        pagamentoPix_btn.setBounds(90, 160, 400, 70);

        cartaoDebito_btn.setText("<cartao-debito>");
        cartaoDebito_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaoDebito_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cartaoDebito_btn);
        cartaoDebito_btn.setBounds(90, 250, 400, 80);

        cartaoCredito_btn.setText("<cartao-credito>");
        cartaoCredito_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartaoCredito_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cartaoCredito_btn);
        cartaoCredito_btn.setBounds(90, 350, 400, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(578, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dinheiro_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dinheiro_btnActionPerformed
        //mensagem "pagamento no caixa"
    }//GEN-LAST:event_dinheiro_btnActionPerformed

    private void pagamentoPix_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagamentoPix_btnActionPerformed
        //mensagem "pagamento realizado"
    }//GEN-LAST:event_pagamentoPix_btnActionPerformed

    private void cartaoDebito_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaoDebito_btnActionPerformed
        //mensagem "pagamento realizado"
    }//GEN-LAST:event_cartaoDebito_btnActionPerformed

    private void cartaoCredito_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartaoCredito_btnActionPerformed
        //mensagem "pagamento realizado"
    }//GEN-LAST:event_cartaoCredito_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(opcoesPagamento_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(opcoesPagamento_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(opcoesPagamento_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(opcoesPagamento_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new opcoesPagamento_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cartaoCredito_btn;
    private javax.swing.JButton cartaoDebito_btn;
    private javax.swing.JButton dinheiro_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pagamentoPix_btn;
    // End of variables declaration//GEN-END:variables
}
